### PR TITLE
Safari support

### LINKED ISSUE #6: Support for Safari on macOS
In the latest Safari 14 for macOS there is support for the standard WebExtensions API - https://developer.apple.com/documentation/safariservices/safari_web_extensions 

Maybe it would be possible without much changes to support Safari as well? 
For the publishing side it might be a little more complicated since it requires Mac App Store publication but it might be feasible.

### PR DESCRIPTION
**Pull request by osnr**
Fixes #6. 

It's a bit messy, but it at least it doesn't affect the core of TabFS much.
Apple are right that their internal API is mostly compatible with WebExtensions now, but they require way more Apple-specific bureaucracy than I'd like _around_ that API, to get everything set up and talking in the first place. So this PR is mostly just passthrough stuff to deal with Apple's requirements (macOS app, native extension embedded in app, sandbox-avoiding XPC service, long-lived TabFS WebSocket server subprocess of XPC service, communications among these). The key files are probably [SafariWebExtensionHandler.swift](https://github.com/osnr/TabFS/blob/safari/extension/safari/TabFS/TabFS%20Extension/SafariWebExtensionHandler.swift) and [TabFSService.swift](https://github.com/osnr/TabFS/blob/safari/extension/safari/TabFS/TabFSService/TabFSService.swift) and [TabFSServer/main.swift](https://github.com/osnr/TabFS/blob/safari/extension/safari/TabFS/TabFSServer/main.swift).

I haven't tested the fs that much yet, but the basic stuff seems to work. (Maybe the tests should be made browser-portable?)

**I would love it if someone could try this on their own machine before I merge it. :-)**

**See [`extension/safari`](https://github.com/osnr/TabFS/tree/safari/extension/safari) for very rough instructions.** See also:
- https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension#2957926
- https://mackuba.eu/notes/wwdc20/meet-safari-web-extensions/
- https://blog.yimingliu.com/2018/11/14/notes-on-porting-a-safari-extension-to-a-safari-app-extension/ (about the older App Extension model which the newer Web Extension stuff is built on top of / assumes that you know about)

I'd like to write more about architecture of all this (I'm forced to use a lot of different process and security domains) -- maybe in the next sponsor newsletter.
image
image

### CODE REVIEW

**Comment by bjtitus** [comment]
Thank you so much for taking this on @osnr! I took a look at implementing this but was quickly dissuaded by the XPC stuff and implementing the message passing.

I was able to build and run this on my machine with no changes (other than signing). There are a lot of errors logged to the web console, but things do appear to work great!

**Comment by osnr** [comment]
Awesome, thanks for trying this! What kind of errors have you been seeing in the console?

**Comment by bjtitus** [comment]
I think the `WebSocket network error` could just be timing with the socket starting up.

There's occasional `"Failed to load resources: The operation couldn't be completed. (Cocoa error -1000.)"` errors.

Then just some possibly expected errors from within `background.js`:
* A `timeout` from `background.js:687`
* Maybe the `UnixError` log in `background.js:28`

Screen Shot 2021-02-14 at 10 58 45 AM

Here's the full console log with a few more errors if you're interested:
[logs.txt](https://github.com/osnr/TabFS/files/5978218/logs.txt)

I tried a few of the writeable commands again and I think everything is working as expected. Not sure why deleting a file wasn't working before.

**Comment by osnr** [comment]
All good -- thanks for the report!

**Pull request merged**
