### PR TITLE
Fix body.html for larger files and UTF-8 contents.

### PR DESCRIPTION
**Pull request by rumpeltux**

### CODE REVIEW

**Comment by osnr** [comment]
Thanks -- do you have an example of a page which this fixes?

**Comment by rumpeltux** [comment]
Sure, here’s an example. Pretty much any larger page will do.

    dd if=/dev/random bs=1M count=1 of=/tmp/garbage.html
    chrome /tmp/garbage.html
    cat tabs/last-focused/text.txt

```js
background.js:925 RangeError: Maximum call stack size exceeded
    at Object.read (background.js:130:28)
    at onMessage (background.js:920:35)
```

**Comment by osnr** [comment]
Hmm. I can't replicate that in Safari or Chrome on my Mac -- I'll take your word for it. I wonder if there's OS-dependent behavior here or something.

**Comment by osnr** [comment]
Thanks again.

**Pull request merged**
