### PR TITLE
Append user-defined CFLAGS

### PR DESCRIPTION
**Pull request by catleeball**
Allow CFLAGS present in the user's environment be appended to EXTRA_CFLAGS.

### CODE REVIEW

**Comment by osnr** [comment]
thanks! I re-cloned this, but it doesn't seem to build out of the box for me on macOS?

```
~/aux/tabfs-aux/fs $ make
Makefile:14: *** Recursive variable `CFLAGS' references itself (eventually).  Stop.
```

**Comment by catleeball** [comment]
Oh interesting!

`::=` in GNU and POSIX Makefiles should do "simple" expansion. Does Mac use a BSD or Apple-specific make? Maybe `:=` would be more compatible.

I'll grab my macbook and poke at it and will update this PR if I find anything out. :)

**Comment by catleeball** [comment]
Ah, checking on my Mac `:=` and `::=` both try to recursively expand. I'll just split a separate variable name then.

**Comment by catleeball** [comment]
Sorry for a few extra commits along the way there! I was using git push/pull to get the code from my desktop where I was editing to my mac to test. I worked it out, using `+=` and fixing a silly extra var I stuck at the end of the mac make string.

**Comment by osnr** [comment]
no worries! thanks for this!

**Pull request merged**
